# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dispositivo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64ispositivo.proto\"D\n\x08\x41parelho\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02on\x18\x02 \x01(\t\x12\x13\n\x06volume\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\t\n\x07_volume\"-\n\rAparelhosBook\x12\x1c\n\taparelhos\x18\x01 \x01(\x0b\x32\t.Aparelhob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dispositivo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_APARELHO']._serialized_start=21
  _globals['_APARELHO']._serialized_end=89
  _globals['_APARELHOSBOOK']._serialized_start=91
  _globals['_APARELHOSBOOK']._serialized_end=136
# @@protoc_insertion_point(module_scope)
